### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Snak3Doc** [Pergor/ADV_Mods#2]
First of thank you for your awesome list of mod extensions their really useful and the cpr mod is a godsend.

I was wondering if you might be interested in making a small extension for ACE, basically, an action on arrested players/ai to force them down into the vanilla, hands handcuffed behind back kneeling on the ground animation, and an action to make them stand back up of course?

Thanks again for your awesome work.

**Comment by Pergor** [comment]
Technically that should be possible.
The way ACE handles the handcuffed animation is a bit more complicated than just moving the unit in the animation, as that animation might break as soon as the player vaults for example.
But there's probably a way to rewrite the EventHandler that ACE adds to the unit upon capture.
I'll look into it.

**Comment by Pergor** [comment]
Take a look at adv_aceCaptive, it's not fully tested yet, but it might do what you wanted:
https://github.com/Pergor/ADV_Mods

Unfortunately, the way ace handles these animations seems to not allow a smooth transition to the new animation. I'm currently looking into it.

**Comment by Snak3Doc** [comment]
Awesome thanks for having g a crack at it, I'm at uni for another 5 hours but I'll have a look when I get home

**Comment by Snak3Doc** [comment]
Had a go with it on my dedi server works great on players, though the ai spin on the spot following the closest player/ai it considers an enemy (it's just a little creepy) not sure if it's vcom ai causing it or vanilla yet but theirs functions for both that disable ai movement, which could fix it, only other thing is the captured player/ai rotate back to the direction they started the animation at if your escort them somewhere.

**Comment by Pergor** [comment]
No, the turning of AI is vanilla as well. That might be fixed.

Escorting a kneeling person... let's at least say it's quite rude to do so. ;) I'd tell your players to only escort a captive if he's standing. But I might look into that as well.

**Comment by Pergor** [comment]
Ok, I did it: With the new version you can't escort a captive as long as they're kneeling and the AI won't turn around anymore.

The problem with the starting rotation hasn't been solved since it depends on the animation. The kneeling animation is a cut scene animation - these are a bit wonky for uses like that.

**Comment by Snak3Doc** [comment]
Was just about to post about it the animation not working and noticed you had updated it 3 hours ago, any reason for the change to the sitting animation instead of the kneeling one?

**Comment by Snak3Doc** [comment]
Thought you might be interested in this as well seeing as you seem to get annoyed with the same ace stuff as me ;), it lets you add an addaction to an object that returns stamina to full. https://pastebin.com/JTGnf6SF just place an ai called "stambitch" somewhere in the map and disable his movement and call the sqf with an add action on an object, I'm trying to work out if its possible to turn it into a consumable that returns the stamina over x time at the moment.

**Comment by Pergor** [comment]
Thank you, but my community and I play with advancedfatigue enabled since it's a player limitation that's quite welcome for our playstyle.

**Comment by Snak3Doc** [comment]
Yeah we use advanced fatigue as well, with this im essential trying to make a can of red bull that can return some of your stamina, out of interest what settings do you use for advanced fatigue?

**Comment by Pergor** [comment]
class ace_advanced_fatigue_enabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_fatigue_performanceFactor {
    value = 1.5;
    typeName = "SCALAR";
    force = 0;
};
class ace_advanced_fatigue_recoveryFactor {
    value = 1.8;
    typeName = "SCALAR";
    force = 0;
};
class ace_advanced_fatigue_loadFactor {
    value = 0.9;
    typeName = "SCALAR";
    force = 0;
};
class ace_advanced_fatigue_terrainGradientFactor {
    value = 0.9;
    typeName = "SCALAR";
    force = 0;
};
