### ISSUE TITLE
CPR Stops working after first patient stabilised (Fixed in master?)

### ISSUE THREAD

**Issue by Snak3Doc** [Pergor/ADV_Mods#3]
Using the current release of ADV_CPR the cpr & defib actions in stops appearing after you have stabilised your first patient.

Running with the latest files from the master on GitHub, seems to fix it although I'm not sure if it's intended for medics to be able to cpr/defib patients that still have open wounds (seem to only work once) which I like cause it makes sense for eg a patient with a bunch of cuts and scrapes on their leg with a tourniquet on it to have one medic start cpr/stabilising the patient while the other finishes the wounds.

**Comment by Pergor** [comment]
It should be fixed in master (it's currently being tested).

Being able to do CPR while patient is bleeding is intended. The probability for successful resuscitation drops heavily though.

**Comment by Snak3Doc** [comment]
Awesome thanks for clearing that up.
We have run the master version for about 4 missions with 10-15 players and haven't come across any issues yet.

**Comment by Pergor** [comment]
That's great to hear, thank you for your feedback!

**Comment by Pergor** [comment]
Resolved with 8584876 and c7d59ec
