### ISSUE TITLE
ADV - ACE CPR - fn_canCPR.sqf returns always false

### ISSUE THREAD

**Issue by Wyqer** [Pergor/ADV_Mods#4]
Hey there.

We've just updated from 1.3 to the actual 1.4.4 version of the script and during tests of the AED, we've encountered issues as the patient will not wake up "ist nicht mehr zu retten" (STR_ADV_ACECPR_CPR_FATAL). We've enabled the missionNamespace debug variable and went through some tests.

What we've done:
* Shot someone in the revive state (no pulse, etc.)
* Bandage the patient until he's all blue
* Used the surgical kit to prevent reopening of the wounds
* Gave blood to the patient until there isn't the hint that he had lost a lot of blood anymore
* Gave a morphine to get rid of the pain of the patient
* Gave 1-2 epinephrine for CPR chance increase

**---- Until this point it's all like we've done it before in the old version. With this CPR always worked as intended in the old version. We haven't changed any ACE server settings, just updated this mod ----**

* Used 2 - 3 times the AED -> patient always woke likely up (raised the head) and immediately returned into the revive state (no pulse again). Also no message in the ace medical diary at the bottom of the medic dialog

**---- We used a PAK, to reset the patient and did all the same steps until usage of the AED, as we now wanted to try normal CPR. ----**

* Used CPR -> Diag said dice roll wasn't inside the probability (so everything was fine)
* Continued CPR -> Once the dice roll was inside the probability, patient raised the head again and immediately fell back into the revive state. And from this point on the patient always gave the message that he will not wake up (FATAL string).

With some look at the code we are very confident, that something with the `ace_medical_reviveStartTime` is messed up. Before the "permanent FATAL string" the patient had a value for this variable on himself. As soon as we get the FATAL strings, the value for the variable is nil, but he's still in the revive state (no respawn or anything). Also a PAK still worked afterwards.

So we guess that somehow (maybe with the `addTime`) the `ace_medical_reviveStartTime` variable will get nil. And because of that the

    alive _target && (_inRevState && (_startTime+(_maxTime/_quotient)) > CBA_missionTime)

will always return false, as the reviveStartTime + the server setting time (1200 on our server) is always below the current missiontime.

Any thoughts or confirmations from somewhere else?

**Comment by Wyqer** [comment]
Well, I got the issue in the code.
It's for example the last commit
https://github.com/Pergor/ADV_Mods/commit/85848761cb747084605f391d979972639ae26015#diff-7301143ddeff2c0c8013a370e10105c0

    if ( _reviveEnabled ) then {

should be

    if (_reviveEnabled > 0) then {

and the same for the `AED_local` function.

Some snippets of the local client log which made the error very obvious afterwards.

---

**CPR_local**

13:59:39 "[""adv_aceCPR - custom CPR is being executed""]"
13:59:39 "[""adv_aceCPR - added time was 15.5728. New reviveStartTime was 5227.39, with a difference to cba_missiontime of 160.227 seconds.""]"
13:59:39 "[""adv_aceCPR - probability started at 15, with a adv_aceCPR_probabilities of [40,15,5,85]""]"
13:59:39 "[""adv_aceCPR - probability has been reduced by 7.66667 due to morphine. New probability is 7""]"
13:59:39 "[""adv_aceCPR - probability has been raised by 15.3333 due to epinephrine. New probability is 22""]"
13:59:39 "[""adv_aceCPR - the patient has a bloodloss of 0""]"
13:59:39 "[""adv_aceCPR - probability has been reduced by any due to blood loss. New probability is 22""]"
13:59:39 "[""adv_aceCPR - resulting probability was at 22 per-cent, and the dice-roll was 4.""]"
13:59:39 Error in expression <ace_medical_epinephrine_insystem",0];


if ( _reviveEnabled ) then {
call {
if (>
13:59:39   Error position: <if ( _reviveEnabled ) then {
call {
if (>
13:59:39   Error if: Typ Zahl, erwartet Bool
13:59:39 File adv_aceCPR\functions\fn_CPR_local.sqf [adv_aceCPR_fnc_CPR_local], line 44

---

**AED_local**

14:00:01 "[""adv_aceCPR - custom CPR is being executed""]"
14:00:01 "[""adv_aceCPR - custom CPR on target not possible""]"
14:00:13 "[""adv_aceCPR - target is not local to the caller""]"
14:00:13 "[""adv_aceCPR - probability was at 85 per-cent, and the dice-roll was 20.""]"
14:00:13 Error in expression <_medical_inCardiacArrest",false,true];

if ( _reviveEnabled ) then {

_target se>
14:00:13   Error position: <if ( _reviveEnabled ) then {

_target se>
14:00:13   Error if: Typ Zahl, erwartet Bool
14:00:13 File adv_aceCPR\functions\fn_AED_local.sqf [adv_aceCPR_fnc_AED_local], line 31

**Comment by Pergor** [comment]
Thank you very much for your feedback.
Obviously I made a mistake with the _reviveEnabled query. Will fix it immediately. Thank you for clearing that up.

**Comment by Wyqer** [comment]
Just merge the pull request. It wasn't that big mistake. Something like that can always happen ^^
Just wondering, why no one already noticed and/or reported that one, as it's an edit from 8 days ago.

**Comment by Pergor** [comment]
Someone actually did report it, but I wasn't at home to delve into the problem. ;)

**Comment by Pergor** [comment]
Resolved with c7d59ec
