### ISSUE TITLE
Feature Request ADV_SPLINT

### ISSUE THREAD

**Issue by blindbat2006** [Pergor/ADV_Mods#7]
Option in settings to have the splint "fall off" after a time period i.e 5 mins. This would mean that either another splint would need to be applied or player would need a PAK to get fully healed.
I think the splint should only be a temporary fix for broken bones.

**Comment by Pergor** [comment]
Unfortunately that's not as easy as it may sound. ACE³ has a whole framework for the reopening of wounds. All ADV - ACE Splint does is resetting the ace_medical_bodypartstatus and ace_fnc_setHitPointDamage to 0 for the concerned limbs. There are quite a couple of variables to be stored (BIS and ACE handle hitpoints differently, and so do I) that don't necessarily have much in common, but are all needed if hitpoint damage is concerned.

It would need a complete rewrite of the main function of ADV - ACE Splint. I'll look into it, but given that it's no feature that I'd consider using, it might receive lower priority.

**Comment by Pergor** [comment]
I tried to implement a reopening chance for the splints:
https://github.com/Pergor/ADV_Mods/commit/ccd9b31d95a34357bdaa04b6bcba19f3c4ffe9df
You might want to check if it works like it should.

**Comment by blindbat2006** [comment]
Ok thanks. My thinking was it would be like CPR but instead of adding time to a bleed out it would countdown then set the hitpoints back on the limbs with splints. I will do abit of testing now

**Comment by Pergor** [comment]
I now added cba settings to ADV - ACE Splint and additional settings for the probability to fall off, for the time a splint takes to fall off and a probability for the splint to be reuseable.
