### ISSUE TITLE
Feature Request: CBA Settings Support

### ISSUE THREAD

**Issue by DeliciousJaffa** [Pergor/ADV_Mods#8]
Your mods would be much more accessible if the average player can edit settings through the Addon Options where all their other ace, etc settings are.

https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System

**Comment by Pergor** [comment]
I'm looking into it.

**Comment by Pergor** [comment]
I've added CBA settings and additional functionality, like reusability for splints after they've fallen off.

**Comment by DeliciousJaffa** [comment]
You only manually copied across the stuff for aceSplint, you missed out aceCPR

**Comment by Pergor** [comment]
One step at a time.

**Comment by Pergor** [comment]
There you go: https://github.com/Pergor/ADV_Mods/commit/b3715824df2fc115a31e0bbdf8d2fb79d30b5573
